name: Build Weather App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev g++

    - name: Build weather app
      run: g++ main.cpp WeatherClient.cpp -o weather_app -lcurl

    - name: Run weather app (with test city)
      run: ./weather_app London
      env:
        API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
